#!/usr/bin/env python3
"""Generate icon_data.h from peanutbuttyicon.jpg: ARGB byte quads at several
sizes for the _NET_WM_ICON window property. Run: python3 gen_icon.py"""
from PIL import Image
SIZES = (128, 32)
src = Image.open("peanutbuttyicon.jpg").convert("RGBA")
out = ["/* Generated by gen_icon.py from peanutbuttyicon.jpg. Do not edit. */",
       "#include <stdint.h>",
       "typedef struct { int size; const uint8_t *argb; } IconLevel;"]
for s in SIZES:
    im = src.resize((s, s), Image.LANCZOS)
    px = im.tobytes()  # RGBA
    quads = []
    for i in range(0, len(px), 4):
        r, g, b, a = px[i:i+4]
        quads.append(f"{a},{r},{g},{b}")
    out.append(f"static const uint8_t icon_{s}[] = {{")
    for i in range(0, len(quads), 8):
        out.append("  " + ",".join(quads[i:i+8]) + ",")
    out.append("};")
out.append("static const IconLevel ICON_LEVELS[] = { " + ", ".join(f"{{{s}, icon_{s}}}" for s in SIZES) + " };")
out.append("#define ICON_LEVEL_COUNT " + str(len(SIZES)))
open("icon_data.h", "w").write("\n".join(out) + "\n")
src.resize((256, 256), Image.LANCZOS).save("peanutbutty.png", optimize=True)
print("wrote icon_data.h and peanutbutty.png")
